Did some minor changes

diff --git a/.github/workflows/MainMigrationWorkflow.yml b/.github/workflows/MainMigrationWorkflow.yml
--- a/.github/workflows/MainMigrationWorkflow.yml
+++ b/.github/workflows/MainMigrationWorkflow.yml
@@ -232,13 +232,32 @@ jobs:
       - name: 💾 Checkout code
         uses: actions/checkout@v2
       - name: 🤖 Download Migration Client
-        run: |
-           cd utils/migration-client
-           wget -qq --waitretry=5 --tries=3 "https://github.com/wso2-extensions/identity-migration-resources/releases/download/v1.0.225/wso2is-migration-1.0.225.zip"
-           unzip -q wso2is-migration-1.0.225.zip -d utils/migration-client
-           rm wso2is-migration-1.0.225.zip
         env:
           MIGRATION_TOKEN: ${{ secrets.MIGRATION_TOKEN }}
+        run: |
+
+          # Define the necessary variables
+          REPO_OWNER="wso2-extensions"
+          REPO_NAME="identity-migration-resources"
+          RELEASE_TAG="v1.0.225"
+          FILE_NAME="wso2is-migration-1.0.225.zip"
+
+          # Get the latest release information
+          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/tags/${RELEASE_TAG}"
+          DOWNLOAD_URL=$(curl -s -H "Authorization: Bearer ${MIGRATION_TOKEN}" ${API_URL} | jq -r ".assets[] | select(.name == \"${FILE_NAME}\") | .browser_download_url")
+
+          # Download the file
+          if [[ -n "$DOWNLOAD_URL" ]]; then
+            echo "Downloading Migration Client..."
+            wget -qq --waitretry=5 --tries=3 "${DOWNLOAD_URL}" -O "${FILE_NAME}"
+            echo "Download completed!"
+            unzip -q "${FILE_NAME}" -d ./utils/migration-client
+            rm "${FILE_NAME}"
+          else
+            echo "Failed to retrieve the download URL for the Migration Client."
+            exit 1
+          fi
+
       - name: 💵 Cache Logs
         id: cache-logs
         uses: actions/cache@v2
