Did some minor changes

diff --git a/.github/workflows/MainMigrationWorkflow.yml b/.github/workflows/MainMigrationWorkflow.yml
--- a/.github/workflows/MainMigrationWorkflow.yml
+++ b/.github/workflows/MainMigrationWorkflow.yml
@@ -243,23 +243,22 @@ jobs:
         #env:
         #MIGRATION_PAT: ${{ secrets.MIGRATION_PAT }}
         run: |
-            redirect_url=$(curl --silent --show-error \
-              --header "Accept: application/octet-stream" \
-              --header "Authorization: token $MIGRATION_PAT" \
-              --request GET --write-out "%{redirect_url}" \
-              "https://github.com/wso2-extensions/identity-migration-resources/releases/download/v1.0.225/wso2is-migration-1.0.225.zip") &&
-            readonly redirect_url &&
-            echo "Download is starting now..." &&
 
-            # Finally, download the actual binary.
-            cd "/home/runner/work/Automating-Product-Migration-Testing/Automating-Product-Migration-Testing/migration-automation" &&
-            curl -LJO --show-error -v \
-              --output "wso2is-migration-1.0.225.zip" \
-              --request GET \
-              "$redirect_url" ||
-            (echo "Error downloading binary." && exit 1) &&
-            echo "Binary download is completed."
+          redirect_url=$(curl --silent --show-error \
+            --header "Accept: application/octet-stream" \
+            --header "Authorization: token ${{ secrets.MIGRATION_PAT }}" \
+            --write-out "%{redirect_url}" \
+            "https://github.com/wso2-extensions/identity-migration-resources/releases/download/v1.0.225/wso2is-migration-1.0.225.zip") &&
+          readonly redirect_url &&
+          echo "Download is starting now..." &&
 
+          # Finally, download the actual binary.
+          cd "/home/runner/work/Automating-Product-Migration-Testing/Automating-Product-Migration-Testing/migration-automation" &&
+          curl -LJO --show-error -v \
+            --output "wso2is-migration-1.0.225.zip" \
+            "$redirect_url" ||
+          (echo "Error downloading binary." && exit 1) &&
+          echo "Binary download is completed."
 
       - name: 💵 Cache Logs
         id: cache-logs
